### PR TITLE
Permutation Calculate

### PR DESCRIPTION
**Pull request by Lalman888**
I added a code that calculate number of permutation in java .

### CODE REVIEW

**Comment by sanskarsri** [comment]
Hey @Lalman888 
remove your insertion sort code as it is causing conflicts and then notify me

**Comment by Lalman888** [comment]
@sanskarsri  I removed the insertion code but it's not changing here

**Comment by Lalman888** [comment]
@sanskarsri Is there any issue now ?

**Comment by sanskarsri** [comment]
No issues your PR is successfully merged

**Pull request merged**
